# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Directory Permissions
        run: |
          chmod -R 777 ./
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA2REWI4GPGCNKJZFX
          aws-secret-access-key: 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
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build laravel
        id: build-php-image
        env:
          ECR_REGISTRY: aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 724017144222.dkr.ecr.ap-southeast-1.amazonaws.com
          ECR_REPOSITORY: apf-app
          IMAGE_TAG: latest
        run: |
          docker build -t apf-app .
          docker tag ‘ECR app repo name’:latest aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 724017144222.dkr.ecr.ap-southeast-1.amazonaws.com/apf-app:$IMAGE_TAG
          docker push aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 724017144222.dkr.ecr.ap-southeast-1.amazonaws.com/apf-app:$IMAGE_TAG
      - name: Build nginx
        id: build-nginx-image
        env:
          ECR_REGISTRY: aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 724017144222.dkr.ecr.ap-southeast-1.amazonaws.com
          ECR_REPOSITORY: apf-nginx
          IMAGE_TAG: latest
        run: |
          docker build -f Dockerfile_Nginx -t apf-nginx .
          docker tag apf-nginx:latest aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 724017144222.dkr.ecr.ap-southeast-1.amazonaws.com/apf-nginx:$IMAGE_TAG
          docker push aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 724017144222.dkr.ecr.ap-southeast-1.amazonaws.com/apf-nginx:$IMAGE_TAG
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ap-demo --query taskDefinition > task-definition.json
      - name: Fill in the new app image ID in the Amazon ECS task definition
        id: app-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: app
          image:  latest
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: AKIA2REWI4GPGCNKJZFX
          AWS_SECRET_ACCESS_KEY: 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

      - name: Fill in the new nginx image ID in the Amazon ECS task definition
        id: web-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nginx
          image: latest
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: AKIA2REWI4GPGCNKJZFX
          AWS_SECRET_ACCESS_KEY: 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

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.web-task-def.outputs.task-definition }}
          service: ap-demo
          Cluster: apf-demo-cluster
          wait-for-service-stability: true
